[tool.poetry]
name = "dbt"
version = "0.1.0"
description = ""
authors = ["Pierre-Louis  Guillou <pierre-louis@modeo.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
